
services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api-gateway
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  # API Gateway - Routes to all microservices
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - claude-service
      - forum-service
      - login-service
      - calendar-service
      - tasks-service
      - scraper-service
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - app-network

  # Claude AI Service
  claude-service:
    build:
      context: ./services/claude-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - ./services/claude-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Forum Service
  forum-service:
    build:
      context: ./services/forum-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./services/forum-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Login Service
  login-service:
    build:
      context: ./services/login-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./services/login-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Calendar Service
  calendar-service:
    build:
      context: ./services/calendar-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./services/calendar-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Tasks Service
  tasks-service:
    build:
      context: ./services/tasks-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - CLAUDE_SERVICE_URL=http://claude-service:3002
    depends_on:
      - claude-service
    volumes:
      - ./services/tasks-service:/app
      - /app/node_modules
    networks:
      - app-network

  # Scraper Service
  scraper-service:
    build:
      context: ./services/scraper-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./services/scraper-service:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge