
CREATE DATABASE IF NOT EXISTS IMOKTOO;
USE IMOKTOO;

CREATE TABLE IF NOT EXISTS migrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    migration_name VARCHAR(255) NOT NULL,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT IGNORE INTO migrations (migration_name) VALUES ('001_initial_setup');
